name: FountainOfYouth
main: com.dsnyder.fountainofyouth.FountainOfYouth
version: 1.2.1-ALPHA
author: Dan Snyder
description: A plugin that allows you to keep an entity a baby forever
commands:
  foyouth:
    usage: /foyouth [subcommand]
    description: Main Fountain of Youth commmand
    aliases: